security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        my_db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            provider: my_db_provider
            anonymous: ~
            form_login:
                  login_path: /login
                  check_path: /login_check
                  default_target_path: user_homepage
            logout: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
